# Generated by Django 4.1.8 on 2023-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='dni')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='nombre_cliente')),
                ('ruc', models.CharField(blank=True, max_length=13, verbose_name='ruc')),
                ('nombre_Empresa', models.CharField(blank=True, max_length=150, verbose_name='nombre_empresa')),
                ('direcccion', models.CharField(max_length=150, verbose_name='direccion')),
            ],
        ),
    ]
