# Generated by Django 4.1.8 on 2023-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('numero_mesa', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
    ]
