# Generated by Django 4.1.8 on 2023-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles_usuario',
            field=models.CharField(choices=[('A', 'administrador'), ('M', 'mesero'), ('c', 'Cocinero')], default='M', max_length=1),
        ),
    ]
